
//import static Login.txtPassword;
//import com.sun.jna.platform.win32.WinBase;

import com.mysql.jdbc.Connection;
import java.awt.HeadlessException;
//import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
//import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
//import java.nio.charset.StandardCharsets;
//import java.nio.file.Files;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
//import java.util.ArrayList;
//import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.CipherOutputStream;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
//import sun.net.www.http.HttpClient;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Abdo sniper
 */
public class UserForm extends javax.swing.JFrame {
static String fn="";
static String of="";
DefaultListModel Keyslist=new DefaultListModel();
DefaultListModel Valueslist=new DefaultListModel();
    /**
     * Creates new form UserForm
     */
        String Username ="";
    public UserForm(String _Username) {
        initComponents();
        this.Username = _Username;
        lblUserName.setText(Username);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(195, 153, 69));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1498793656_Gnome-View-Refresh-32.png"))); // NOI18N
        jButton3.setText("view upload file");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1498793420_download-box-open.png"))); // NOI18N
        jButton4.setText("Download");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1498793515_trash.png"))); // NOI18N
        jButton5.setText("Delete");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("All Upload File ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Welcome: ");

        lblUserName.setName("lblUserName"); // NOI18N

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1498793336_old-go-top.png"))); // NOI18N
        jButton7.setText("Upload");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1498793726_Exit.png"))); // NOI18N
        jButton8.setText("Logout");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1498793145_User1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(52, 52, 52)
                                        .addComponent(lblUserName)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(304, 304, 304)
                                .addComponent(jButton8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(jButton4)
                        .addGap(24, 24, 24)
                        .addComponent(jButton5)
                        .addGap(24, 24, 24)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblUserName)
                    .addComponent(jLabel3))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton3))
                .addGap(87, 87, 87)
                .addComponent(jButton8)
                .addGap(313, 313, 313))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        

        
        jTable2 =new JTable();
        td =new DefaultTableModel();
        //td.addColumn("fid");
        td.addColumn("filename");
        jTable2.setModel(td);
        
        
         String dbusername="root";   //database usernaem
        String dbpassword="";   // database password
          String DB_URL  = "jdbc:mysql://localhost/cloud";    //connection String 
       
         try {
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection) DriverManager.getConnection(DB_URL, dbusername, dbpassword);
            PreparedStatement ps = con.prepareStatement("select * from filename where uid=?");
            ps.setString(1,Login.UserID);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
            
                Object []ob={rs.getString(2)};
                td.addRow(ob);
                
            }

            
            jScrollPane1.getViewport().add(jTable2);
            
            
            
            
        } catch (Exception e) {
            
                        System.out.println(e);

        }
       
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
//File file;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
        File file;
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        file = chooser.getSelectedFile();
        File filename=chooser.getSelectedFile();
        String f=filename.getAbsolutePath();
        jTextField1.setText(f);
        String fname=filename.getName();
        fn=filename.getName();
    }//GEN-LAST:event_jButton2ActionPerformed
URL rightUrl;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        
           String win_users=System.getProperty("user.name");

        checkperm ch=new checkperm();
        
        String inp = td.getValueAt(jTable2.getSelectedRow(), 0).toString();
        //inp=of;
        Download downloadfile=new Download();
        if(CheckFile.exists("http://127.0.0.1/"+inp)&ch.checkfiledb(inp, Login.UserID))
        {
            
        try {
            rightUrl = new URL("http://127.0.0.1/"+inp);
        } catch (MalformedURLException ex) {
            Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
        } 
        downloadfile.download(rightUrl,new File("C://Users/"+win_users+"/Downloads/"+inp) );
        
        JOptionPane.showConfirmDialog(null, "Dowloaded file ");
        ////////////////////////////
        
        try {
                
                    
                    String s=md5pass.MD5(Login.txtPassword.trim());
                    String su="";
                    su+=s.substring(0, 2);
                    su+=s.substring(14, 16);
                    su+="x9@1";
            
                
                    
                    FileOutputStream outf;
                    CipherOutputStream cos;
                    try (FileInputStream ef = new FileInputStream("C://Users/"+win_users+"/Downloads/"+inp)) {
                        outf = new FileOutputStream("C:\\Decrypted\\"+inp);
                        byte k[]=su.getBytes();
                        SecretKeySpec key=new SecretKeySpec(k,"DES");
                        Cipher enc=Cipher.getInstance("DES");
                        enc.init(Cipher.DECRYPT_MODE , key);
                        cos = new CipherOutputStream(outf, enc);
                        byte[] buffer=new byte[1024];
                        int read;
                        while((read=ef.read(buffer))!=-1){
                            
                            cos.write(buffer,0,read);
                            
                        }       }
            outf.close();
            cos.close();
            
            JOptionPane.showMessageDialog(null, "Download  file  Done ");
            
                    
                    
                    
                    
                    
                }catch(NoSuchAlgorithmException | IOException | NoSuchPaddingException | InvalidKeyException | HeadlessException e){
                
                JOptionPane.showMessageDialog(null, e);
                }
        
        
        ///////////////////////////////
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

        else 
        
        JOptionPane.showMessageDialog(null, "File Does't exits");
        }
        
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       
        // TODO add your handling code here:
        checkperm ch=new checkperm();
        
        String inp= td.getValueAt(jTable2.getSelectedRow(), 0).toString();

        Download downloadfile=new Download();
        if(CheckFile.exists("http://127.0.0.1/"+inp)&ch.checkfiledb(inp, Login.UserID)){
            
         API api=new API();
         DBAPI dbapi =new DBAPI();
            try {
                
                api.delete(inp);
                dbapi.delete_file_record(inp, Login.UserID);
                if(!CheckFile.exists("http://127.0.0.1/"+inp)){
                
                JOptionPane.showMessageDialog(null, "File Deleted for Server ");
                }
                
            } catch (IOException ex) {
                Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
                        
            }
        else {
        
            JOptionPane.showMessageDialog(null, "File Does't exits");
        
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        //Encrypted file 
        
        
        /*
        String key=Login.txtPassword;
        File ef= new File(jTextField1.getText());
        File outf=new File("C:\\Encrypted\\"+fn);
        
        try {

            CipherAES.encrypt(key, ef, outf);
            JOptionPane.showMessageDialog(null,"Encrypted file ");
        } catch (CryptoException ex) {
         JOptionPane.showMessageDialog(null, ex.getMessage());

        ex.printStackTrace();
        }
        
        */
        
        
       
        try {
            String s=md5pass.MD5(Login.txtPassword.trim());
            String su="";
            su+=s.substring(0, 2);
            su+=s.substring(14, 16);
            su+="x9@1";
            
            
            FileOutputStream outf;
            CipherOutputStream cos;
            try (FileInputStream ef = new FileInputStream(jTextField1.getText())) {
                outf = new FileOutputStream("C:\\Encrypted\\"+fn);
                byte k[]=su.getBytes(); 
                SecretKeySpec key=new SecretKeySpec(k,"DES");
                Cipher enc=Cipher.getInstance("DES");
                enc.init(Cipher.ENCRYPT_MODE, key);
                cos = new CipherOutputStream(outf, enc);
                byte[] buffer=new byte[1024];
                int read;
                while((read=ef.read(buffer))!=-1){
                    
                    cos.write(buffer,0,read);
                    
                }
            }
            outf.close();
            cos.close();
            
           // JOptionPane.showMessageDialog(null, "Encrypted file  Done ");
            
            
            
            
              
       if(jTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Please Select File First !");
        }
        else {
        new Uploadfile("C:\\Encrypted\\"+fn);
        
        
        
   String dbURL = "jdbc:mysql://localhost:3306/cloud";
   String username = "root";
   String passwordDB = "";
		
try (java.sql.Connection conn = DriverManager.getConnection(dbURL, username, passwordDB)) {
			
String sql = "INSERT INTO filename (files, uid) VALUES (?, ?)";
			
PreparedStatement statement = conn.prepareStatement(sql);
			statement.setString(1,fn);
			statement.setString(2, Login.UserID);
			
			int rowsInserted = statement.executeUpdate();
			if (rowsInserted > 0) {
				JOptionPane.showMessageDialog(null,"Upload  successfully!");
			}

			
		} catch (SQLException ex) {
                    
                    //
		}		
	
                }
            
            
            
            
            
            
            
            
        }catch(NoSuchAlgorithmException | IOException | NoSuchPaddingException | InvalidKeyException | HeadlessException e){
            
        JOptionPane.showMessageDialog(null, e);
        
        }


        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
            
        
        Username="";
        Login.txtPassword="";
        
        
        MainCloud maincloud=new MainCloud();
                maincloud.setVisible(true);
                dispose();


// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new UserForm("").setVisible(true);
            }
        });
    }

    private javax.swing.table.DefaultTableModel td;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblUserName;
    // End of variables declaration//GEN-END:variables

    private static class preparedStatement {

        private static ResultSet executeQuery(String sql) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public preparedStatement() {
        }
    }
}
